<?php

return [
    'name' => env('APP_NAME', ''),
    'version' => env('APP_VERSION', ''),
    'environment' => env('APP_ENV', 'production'),
    'locale' => env('APP_LOCALE', 'en'),
    'debug' => env('APP_DEBUG', ''),
    'fallback_locale' => env('APP_FALLBACK_LOCALE', 'en'),
    'faker_locale' => env('APP_FAKER_LOCALE', 'en_US'),
    'maintenance_driver' => env('APP_MAINTENANCE_DRIVER', 'file'),
    'php_cli_server_workers' => env('PHP_CLI_SERVER_WORKERS', 4),
    'bcrypt_rounds' => env('BCRYPT_ROUNDS', 12),
    'log_channel' => env('LOG_CHANNEL', 'stack'),
    'log_stack' => env('LOG_STACK', 'single'),
    'log_deprecations_channel' => env('LOG_DEPRECATIONS_CHANNEL', ''),
    'log_level' => env('LOG_LEVEL', 'debug'),
    'db_connection' => env('DB_CONNECTION', 'sqlite'),
    'session_driver' => env('SESSION_DRIVER', 'database'),
    'session_lifetime' => env('SESSION_LIFETIME', 120),
    'session_encrypt' => env('SESSION_ENCRYPT', false),
    'session_path' => env('SESSION_PATH', '/'),
    'session_domain' => env('SESSION_DOMAIN', ''),
    'broadcast_connection' => env('BROADCAST_CONNECTION', 'log'),
    'filesystem_disk' => env('FILESYSTEM_DISK', 'local'),
    'queue_connection' => env('QUEUE_CONNECTION', 'database'),
    'cache_store' => env('CACHE_STORE', 'database'),
    'memcached_host' => env('MEMCACHED_HOST', '127.0.0.1'),
    'redis_client' => env('REDIS_CLIENT', 'phpredis'),
    'redis_host' => env('REDIS_HOST', '127.0.0.1'),
    'redis_password' => env('REDIS_PASSWORD', ''),
    'redis_port' => env('REDIS_PORT', 6379),
    'mail_mailer' => env('MAIL_MAILER', 'log'),
    'mail_scheme' => env('MAIL_SCHEME', ''),
    'mail_host' => env('MAIL_HOST', '127.0.0.1'),
    'mail_port' => env('MAIL_PORT', 2525),
    'mail_username' => env('MAIL_USERNAME', ''),
    'mail_password' => env('MAIL_PASSWORD', ''),
    'mail_from_address' => env('MAIL_FROM_ADDRESS', 'hello@example.com'),
    'mail_from_name' => env('MAIL_FROM_NAME', '${APP_NAME}'),
    'aws_access_key_id' => env('AWS_ACCESS_KEY_ID', ''),
    'aws_secret_access_key' => env('AWS_SECRET_ACCESS_KEY', ''),
    'aws_default_region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
    'aws_bucket' => env('AWS_BUCKET', ''),
    'aws_use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
    'vite_app_name' => env('VITE_APP_NAME', '${APP_NAME}'),
];
